file_path = '.\setting.txt'  
dict_ = {}

with open(file_path, 'r', encoding='gb2312') as f:
    lines = f.readlines()

# 前12行，key自定义
keys = ['TxtInOut file generated by Arcswat', 'Configuration file path for the parameter template', 'Flow observation data', 'Evapotranspiration observation file', 'Soil moisture observation file', 'Observation files used for ETC analysis', 'SWAT simulation output path', 'Latin Hypercube Sampling results', 'Suggested parameter template configuration file', 'Temporary working directory for multi-threading', 'Parameter iteration weight configuration file', 'Image storage location']
for i in range(12):
    dict_[keys[i]] = lines[i].strip()

# 后面的行，冒号分隔的key-value
for line in lines[12:]:
    key, value = line.split(": ")
    dict_[key.strip()] = value.strip()
p_input=dict_
# print(dict_)
if __name__ == "__main__":
    for i,df in dict_.items():
        print('%s: %s'%(i,df))